### ISSUE TITLE
Window minimization loses calculation results

### ISSUE THREAD

**Issue by Vort** [radioacoustick/Coil64#2]
Reproduction steps:
1. Start `Coil64.exe`.
2. Calculate some coil (results appear on the right panel).
3. Minimize window.
4. Restore window.

Expected result:
Calculation result still displayed.

Actual result:
Right panel state rolls back to initial state (blank if there were no results when program was started).

Tested version:
Coil64 v2.1.14

OS:
Windows 7 SP1 x64

**Comment by radioacoustick** [comment]
Thanks for the signal. This effect is observed only in the application installed using the installation file and is miss in the portable application. We will look for the reason of this.

**Comment by radioacoustick** [comment]
In the new version 2.1.15 of the application, the issue disappeared by itself. Most likely the error is not related to the code of this application, but to a bug in the installation compiler. The issue will be monitored in future. Thanks. Now the issue is closed.

**Comment by Vort** [comment]
@radioacoustick it is too early to close this report:
https://www.youtube.com/watch?v=4ktdMW2oJng

**Comment by radioacoustick** [comment]
So, this issue appears only in specific cases. Sorry, will be looking for...

**Comment by Vort** [comment]
I am using `Coil64-2.1.15-windows-portable.zip` by the way.
Because I can't find x64 portable.

**Comment by radioacoustick** [comment]
I didn't zipping the 64-bit portable version. But you can copy coil64.exe from 64-bit install directory "C:\\Program files\Coil64" to any one and try to launch the app as a portable with clear initialization. Unfortunately, on my Windows 10 the app works correctly. I'll looking for issue on WMware virtual machine. Thanks.

**Comment by Vort** [comment]
I have made a test inside Win7 VM with installer (x64).
First run: no problem.
Second run: problem exists.

**Comment by Vort** [comment]
Reproduction is slightly more complicated:
First run: start it and close it.
Second run: create coil, minimize and restore.

**Comment by radioacoustick** [comment]
I think I could find the cause of the issue. If you'll have some time, you would test the updated executable at this link. 
https://coil32.net/files/Test.zip
Thanks a lot.

**Comment by Vort** [comment]
I did not tested all possible scenarios, but one, which is described in this report, works good now.
So I think it is ok to close this report.
Thanks for the fix and for the program.
I will make another report if find another problem.

**Comment by radioacoustick** [comment]
The source code updated. The report to be closed. Thanks a lot for the help. Will be happy to hear again!
