### ISSUE TITLE
Incorrect closing tag

### ISSUE THREAD

**Issue by Vort** [radioacoustick/Coil64#4]
Wire diameter shows incorrect in results:
![image](https://user-images.githubusercontent.com/1242858/159434796-4ea17728-fd9d-4d85-afcb-11929d1f93a1.png)

Most likely, because of incorrect closing tag here:
https://github.com/radioacoustick/Coil64/blob/9c6b8190cdc8af23a27a0f4f5e33199d68b1476d/mainwindow.cpp#L4907

**Comment by radioacoustick** [comment]
Thank you. The issue was fixed in v2.1.22
