### ISSUE TITLE
Calculation error in findPotCore_I

### ISSUE THREAD

**Issue by vince-er** [radioacoustick/Coil64#6]
There is a calculation error in the findPotCore_I function in file resolves.cpp
double s2 = sqrt(0.5 * (r3 * r3 + r3 * r3)) - r3;

should be

double s2 = sqrt(0.5 * (r3 * r3 + r4 * r4)) - r3;

**Comment by radioacoustick** [comment]
Thanks for the help. Will be fixed in the next cumulative update.

**Comment by radioacoustick** [comment]
> There is a calculation error in the findPotCore_I function in file resolves.cpp double s2 = sqrt(0.5 * (r3 * r3 + r3 * r3)) - r3;
> 
> should be
> 
> double s2 = sqrt(0.5 * (r3 * r3 + r4 * r4)) - r3;

Thanks for the help. Will be fixed in the next cumulative update.

**Comment by radioacoustick** [comment]
The issue was fixed in the 2.1.25 release. Thanks again.
